### ISSUE TITLE
Improve performance for new `inline` option

### ISSUE THREAD

**Issue by brenoprata10** [brenoprata10/nvim-highlight-colors#80]
After neovim 0.10, the new inline option seems to take a big performance hit. I need to check and polish the code to make it faster

**Comment by catgoose** [comment]
I haven't tested this plugin prior to 0.10, but are you experiencing a flicker on textchange event?

**Comment by brenoprata10** [comment]
Are you using any LSP for color highlighting? If so, i've also noticed this issue. If you are using tailwind, I recommend using only the LSP. So set `enable_tailwind = false` and the flicker will go away

**Comment by brenoprata10** [comment]
Yes I am working on a fix for it

**Comment by jorgebef** [comment]
I would love to help out with the issue causing the flicker.
I've checked out another plugin that manages to display the colors inline as virtual text and doesn't flicker while doing so:
https://github.com/luckasRanarison/tailwind-tools.nvim/blob/a95aaf11d9deca884743c9017323c0ffea0015f2/lua/tailwind-tools/lsp.lua#L10

I believe they are taking a debounced request approach as seen in the `debounced_color_request`, however, I don't know what is causing the actual flickering of the virtual text character in this plugin.

**Comment by brenoprata10** [comment]
I've pushed https://github.com/brenoprata10/nvim-highlight-colors/commit/a2a20e8c0136c14e9d6dd759390495773f4959b2 which fixes the flickering while editing. Please give it a try and report any bugs here for me 😄

**Comment by brenoprata10** [comment]
I've just found a few bugs on it, will be reverting for now

**Comment by chrsrns** [comment]
> Perhaps updating on `InsertLeave` or something similar would help? IMO it's not necessary for the colors to change on every keystroke, but just when I finish typing. If I am typing something that is not a color, then the rendered colors would not change anyway; if I'm typing a color, I would only want to see it rendered when I finish doing so. Perhaps this could even be a config option, e.g., `update_autocmd`.

This makes sense to me. I usually use a color picker tool to find and view colors before putting them in code. I don't usually need to see the colors as I type them too.

**Comment by brenoprata10** [comment]
I will check this one out again this weekend

**Comment by brenoprata10** [comment]
I've put some hours in it this morning. I've just pushed the code which fixes the flickering text. 
Could you guys give it a try again?

CC @jorgebef @catgoose

**Comment by serhez** [comment]
@brenoprata10 I still get this:

https://github.com/brenoprata10/nvim-highlight-colors/assets/18057093/c11c359d-246d-4771-993d-9e1903d5181e

**Comment by brenoprata10** [comment]
Could you describe your auto complete setup?

**Comment by brenoprata10** [comment]
Also, could you share this template tag?

**Comment by brenoprata10** [comment]
I've pushed some code. Could you give it a try again?

**Comment by serhez** [comment]
@brenoprata10 with the newer commits, the issue gets worse (most colors now flicker). I also get the following error:
```
Error executing vim.schedule lua callback: ...vim-highlight-colors/lua/nvim-highlight-colors/utils.lua:193: attempt to index a nil value
stack traceback:
	...vim-highlight-colors/lua/nvim-highlight-colors/utils.lua:193: in function 'handler'
	.../neovim/0.10.0/share/nvim/runtime/lua/vim/lsp/client.lua:685: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
```

I use `cmp`. You can find my config [here](https://github.com/serhez/nvim-config/blob/master/lua/plugins/configs/cmp.lua).

Template tag:
```vue
<template>
    <div
        class="relative p-8 lg:p-14 bg-[#ffffff] lg:bg-zinc-50 lg:rounded-xl shadow-md hover:shadow-xl transition-shadow duration-300 ease-in-out overflow-y-auto">
        <button @click="$emit('close')"
            class="absolute top-6 right-7 lg:top-8 lg:right-8 text-zinc-600 hover:text-zinc-300">
            <icon name="heroicons-solid:x" class="h-6 w-6 lg:h-7 lg:w-7" />
        </button>
        <div class="flex flex-col divide-y-2">
            <div class="flex flex-col gap-2 pb-3">
                <h2 class="text-xl font-bold tracking-tight sm:text-2xl sm:leading-tight">{{ model?.title }}</h2>
                <div class="flex flex-col gap-1 text-zinc-700 italic">
                    <h3 class="text-lg tracking-tight sm:text-xl sm:leading-tight">
                        {{ model?.authors.join(', ') }}
                    </h3>
                    <h4 class="text-lg tracking-tight sm:text-xl sm:leading-tight">
                        {{ model?.venue }} - {{ model?.year }}
                    </h4>
                </div>
            </div>
            <div class="flex flex-col gap-4 pt-3">
                <p class="text-zinc-600">{{ model?.abstract }}</p>
                <div class="flex gap-6">
                    <a v-for="link in model?.links" :key="link.title" :href="link.url" :title="link.title"
                        class="text-zinc-600 transition hover:text-zinc-300" rel="me nofollow noopener" target="_blank">
                        <icon :name="link.icon" class="h-6 w-6" />
                    </a>
                </div>
            </div>
        </div>
    </div>
</template>
```

**Comment by brenoprata10** [comment]
The nil issue was fixed already. Please update the plugin. 
As for the colors. it's hard to belive it could get worse with the code that was added. Could someone else here test the latest changes?

**Comment by serhez** [comment]
Would it not be possible to change the events listed [here](https://github.com/brenoprata10/nvim-highlight-colors/blob/5e5fff3396b9b626383d42c70d3253ce420e3079/lua/nvim-highlight-colors/init.lua#L194) to `InsertLeave` or something similar, instead of `TextChanged`?

**Comment by brenoprata10** [comment]
Will give it a try later

**Comment by serhez** [comment]
Here is another screen recording with the newer changes:


https://github.com/brenoprata10/nvim-highlight-colors/assets/18057093/d45b088d-1b35-4d4e-ba21-79c7f8b3376a

**Comment by brenoprata10** [comment]
I have modified the autocmd as asked. Could you please check if things are still working properly?

**Comment by brenoprata10** [comment]
Now the colors will not highlight when user deletes a line with `dd` or use `X` in normal mode.
Does anyone knows of an autocmd that I could use to handle these cases?

**Comment by serhez** [comment]
Maybe `TextChanged` actually covers this (changes in normal mode) and `TextChangedI` covers changes in insert mode? I'm reading [here](https://tech.saigonist.com/b/code/list-all-vim-script-events.html) and [here](https://gist.github.com/dtr2300/2f867c2b6c051e946ef23f92bd9d1180). Perhaps just removing `TextChangedI` from the original list of events would solve the issue?

**Comment by brenoprata10** [comment]
You're right! 
Changing TextChangedI with InsertLeave fixes the flickering and the plugin still works fine :)

**Comment by brenoprata10** [comment]
I've pushed the code. Please give it a go and let me know if you find any issues

**Comment by Bekaboo** [comment]
Still experiencing slow scrolling when there are many color blocks on the screen.

**Comment by brenoprata10** [comment]
I've checked that too. And I am afraid there is not much I can do. The plugin has a really good "no unnecessary repaints" approach and my bet it's actually neovim struggling to render so many of them :(

**Comment by brenoprata10** [comment]
This only happens for `virtual`. If the performance hit is too much, you can switch to `background` or `foreground`

**Comment by Bekaboo** [comment]
I prefer the style of `virtual`. I will stay on nvim-colorizer for now which does not have this performance issue when using `virtual`.

**Comment by brenoprata10** [comment]
No problem :)

**Comment by rodhash** [comment]
For me what seems to be hitting really hard the performance is the `WinScrolled` autocmd, changing to `CursorHold` fixed it to me at the cost of a small delay to re-render things.

I'm using `updatetime=100` and the this mitigates quite well the re-render delay (when using virtual style).
